### ISSUE TITLE
Edit my Account Incorrect password

### ISSUE THREAD

**Issue by ghost** [kevinwbaker/Echelon#3]
Upon trying to submit an account change you are greeted with "Error: You have supplied an incorrect current password" on the origional admin account.

I am 100% sure the password is correct from the email that was sent to me.

**Comment by kevinwbaker** [comment]
My fault, slight error on line 43 of echelon/actions/edit-me.php.
Change line so that it reads
$mem->reAuthUser($cur_pw, $dbl); // check user current password is correct
